### ISSUE TITLE
How do you track pageviews?

### ISSUE THREAD

**Issue by connor11528** [Kapiche/vue-segment-analytics#1]
I added the package as outlined in the readme and added a destination for Google Analytics into Segment

I'm looking at the docs for [destinations/google-analytics](https://segment.com/docs/destinations/google-analytics/#page-screen) because want to track page views.

I'm using Laravel for routing (so no vue-router). How do I run a script to track a pageview with segment and this package?

**Comment by rstuart85** [comment]
You can see where in the code the library makes the call when a router is available [here](https://github.com/Kapiche/vue-segment-analytics/blob/master/src/index.js#L19).

Basically, you want to use `Vue.$segment.page()`.

**Comment by connor11528** [comment]
Okay very cool thank you
