### ISSUE TITLE
Update Analytics to 2.0

### ISSUE THREAD

**Issue by cefjic** [Kapiche/vue-segment-analytics#254]
Hello

Segment Analytics 1.0 will be deprecated at first semester 2020. When I turn 2.0 on, a big part of my tracking are breaking. I think it is because the plugin is not updated with Analytics 2.0. Someone can update it ? https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

I use vue-segment-analytics in v0.5.0

Thanks

**Comment by wallies** [comment]
Hi @cefjic. We have had Analytics 2.0 turned on for awhile now, and everything seems fine. 
Do you have any errors or screenshots you can share around what you are seeing.
