### ISSUE TITLE
Optional name?

### ISSUE THREAD

**Issue by haaspors** [Kapiche/vue-segment-analytics#3]
Should it be possible to disable `to.name` used as name for a page? Our Vue app names all routes, but we don't want the `name` attribute in segment.

```
      config.router.afterEach((to, from) => {
        // Make a page call for each navigation event
        window.analytics.page(config.pageCategory, to.name || '', {
          path: to.fullPath,
          referrer: from.fullPath
        })
      })
```

**Comment by haaspors** [comment]
Workaround is obviously to do `router.afterEach` manually and not inject router into `Vue.use(VueSegmentAnalytic, {...});`

**Comment by rstuart85** [comment]
I'm not sure the above snippet address your issue does it? It will still send `to.name` if it exists.

**Comment by haaspors** [comment]
that was for reference (taken from `index.js`).. sorry

**Comment by rstuart85** [comment]
Is there a reason why you don't want the name in segment?

**Comment by haaspors** [comment]
If I understand correctly some of our segment destinations would treat page(category, name) as custom events. Hence charging us for events. A normal page() which is what segment tell you in their script snippets doesn't do this.
