### ISSUE TITLE
First route change isn't notified

### ISSUE THREAD

**Issue by gabriel-amram** [Kapiche/vue-segment-analytics#4]
The first route change isn't logged if the analytics.js script takes time to load.

The `index.js` waits for the `init` callback before registering the `afterEach` guard to the router. This causes the guard to be registered AFTER the first route is reached, thus not logging the `page` event.

Instead, the `afterEach` guard should be registered even when waiting for the analytics.js to load and the factory will take care of actually sending the event when the script loads.

**Comment by rstuart85** [comment]
Thanks for your help with this @gabriel-amram
