### ISSUE TITLE
Load Segment after initial page load to eliminate render blocking

### ISSUE THREAD

**Issue by Alex61NN5** [Kapiche/vue-segment-analytics#7]
Hey There,

Is it possible to load the segment api script at the end of the `</body>`?

currently what is happening is it is loading in the `<head>` which Isn't ideal because if you have multiple segment connections, GA, GTM, etc. it blocks the render of the page thus bringing the performance of your website down.

**Comment by Alex61NN5** [comment]
Update on this please??

**Comment by cjrh** [comment]
Hi @Alex61NN5 !

Sorry about the delay in replying, I missed your original comment. You have a point about the order of loading, your suggestion makes sense. But we don't have a lot of time to look at this immediately. Would you be able to put together a pull request for the required changes?

**Comment by rstuart85** [comment]
@Alex61NN5 this library does load segment asynchronously (that's the default operation of load-script).

Can you give some more information about what you have seen to suggest this isn't happening?
