### ISSUE TITLE
router mode only works for first view

### ISSUE THREAD

**Issue by XavierOlland** [Kapiche/vue-segment-analytics#9]
I didn't have that issue with 0.3.0, but I do now with 0.3.2

The first view when I load is sending the page event, but then navigating doesn't register anyt event. Other event calls are working fine.

**Comment by XavierOlland** [comment]
I confirm, it works fine with 0.3.1

**Comment by thetre97** [comment]
It appears the change where the afterEach function is moved outside of the init callback broke this - 
It uses ` analytics = init(...` value, instead of window.analytics.

**Comment by rstuart85** [comment]
@thetre97 can you link me to a commit with that change?

**Comment by thetre97** [comment]
@rstuart85 I believe it is this one - https://github.com/Kapiche/vue-segment-analytics/commit/1c8d851755d66bd1c25b6b57bb4760279b15407e#diff-26f1fb071359c1dbf08651dd9b5a2ac1

**Comment by lukas-vollmer** [comment]
@thetre97 yes, this merge is the reason for this bug. But this one fixes #4 

The solution is pretty simple:

Change:
`let analytics = init(config, () => {})
  
  // Page tracking
  if (config.router !== undefined) {
    config.router.afterEach((to, from) => {
      // Make a page call for each navigation event
      window.analytics.page(config.pageCategory, to.name || '', {
        path: to.fullPath,
        referrer: from.fullPath
      })
    })
  }`

to:

`let analytics = init(config, () => {})
  
  // Page tracking
  if (config.router !== undefined) {
    config.router.afterEach((to, from) => {
      // Make a page call for each navigation event
      window.analytics.page(config.pageCategory, to.name || '', {
        path: to.fullPath,
        referrer: from.fullPath
      })
    })
  }`

Just change "analytics.page" > "window.analytics.page", but let the afterEach outside the callback. Can someone create a Pull Request or give me access.

Best

**Comment by cjrh** [comment]
Now that I've merged #63, is this issue still relevant? (I have not gone through the discussion here in great detail)

**Comment by XavierOlland** [comment]
I'll try to run some test over the next days

**Comment by lukas-vollmer** [comment]
@cjrh thanks for merging, @rstuart85 an update on npm would be nice (of course after testing :-))
